// Generated by CoffeeScript 1.10.0
(function() {
  var app, conf, pmx, probe;

  pmx = require('pmx');

  probe = pmx.probe();

  conf = pmx.initModule({
    widget: {
      type: 'generic',
      logo: 'http://www.creativetechs.com/iq/tip_images/TerminalApp-Icon.png',
      theme: ['#111111', '#1B2228', '#807C7C', '#807C7C'],
      el: {
        probes: false,
        actions: false
      },
      block: {
        actions: false,
        issues: false,
        meta: false,
        cpu: false,
        mem: false,
        main_probes: ['Port']
      }
    }
  });

  probe.metric({
    name: 'Port',
    value: function() {
      return conf.port;
    }
  });

  probe.metric({
    name: 'website',
    value: function() {
      return conf.website || (__dirname + "/website.js");
    }
  });

  app = require(conf.website);

  pm2.connect(function(err) {
    var server;
    if (err) {
      return console.error(err.stack || err);
    }
    server = new Server();
    return app.use('/api', server.server.handle);
  });

  app.listen(conf.port);

}).call(this);

//# sourceMappingURL=app.js.map
