// Generated by CoffeeScript 1.12.7
(function() {
  var app, bodyParser, cookieParser, express, session, session_opts;

  express = require('express');

  cookieParser = require('cookie-parser');

  session = require('express-session');

  bodyParser = require('body-parser');

  session_opts = {
    key: 'lgp-monitor',
    secret: '$W%VDwe3r4wf#$EQ',
    resave: true,
    saveUninitialized: true,
    cookie: {
      maxAge: 86400 * 1000 * 7
    }
  };

  app = express();

  app.set('views', __dirname + "/views");

  app.set('view engine', 'jade');

  app.use('/static', express["static"](__dirname + "/static"));

  app.use(cookieParser());

  app.use(session(session_opts));

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(bodyParser.json());

  app.get('/', function(req, res) {
    return res.render('index');
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=website.js.map
